GOOGLE_APP_ID: "597860078801-a2li20209vuptig4rrqq0eibl7nr0m2p.apps.googleusercontent.com"
GOOGLE_APP_SECRET: "Eap8N0cnCGNYg3baQom_v5v7"

TWITTER_APP_ID: 'FmcdKvfBANeU2jReXvOHaEJiO'
TWITTER_APP_SECRET: 'pP7g1d67Xr1z6A2WXrPLh9HPrLTxsbymkCcuy6R4QumBA6lWrJ'

FACEBOOK_APP_ID: "381233352389029"
FACEBOOK_APP_SECRET: "ea43b22bce2f9e992ce50904aa069bcd"

SECRET_KEY_BASE: '2253eefd7e456219d7629c18a1fca4d7cbb83f146cb98963c57f3de932f69729f4d6785462430114c3594918b4ffb31eb79b087f3d477d07217f130e214f77d0'
RDS_USERNAME: 'uglymy'
RDS_PASSWORD: 'DBuglymy'
RDS_HOSTNAME: 'aa1h5cpj0093yqg.cgl2xnrbitiw.ap-southeast-1.rds.amazonaws.com'
RDS_PORT: '3306'
RDS_DB_NAME: 'ebdb'
CAPTCHA_ID: "6LfR118UAAAAAI7hXF3EzHb5i5U2VKKXrxdtXPBb"
CAPTCHA_SECRET: "6LfR118UAAAAAJ2LUd5MVVbm3NbjdKaOOZUFC08C"
GMAIL: "bebojezaze@gmail.com"
GMAIL_PASSWORD: "wowthisisgood"
AWS_ACCESS_KEY_ID: 'AKIAIKNWBQAZ5XD55NSQ'
AWS_SECRET_ACCESS_KEY: '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'
S3_REGION: 'ap-southeast-1'
S3_BUCKET: 'ugly-my-image'
